// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://coknmsjmzoctmaoggnpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNva25tc2ptem9jdG1hb2dnbnBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MDczNjYsImV4cCI6MjA2NTM4MzM2Nn0.V_JcPkgjlYpL960H2VQ8aa2oU23MOepN_gi6eYwLzZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);